# Generated by Django 6.0.2 on 2026-04-03 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_is_deleted_subscription_is_deleted'),
        ('publicpages', '0008_alter_aboutteammember_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_products_allowed', models.PositiveIntegerField(default=50, help_text='Maximum number of active products the vendor can list.')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission fee percentage applied to vendor sales (e.g., 5.00 for 5%).', max_digits=5)),
                ('can_feature_products', models.BooleanField(default=False, help_text='Whether this vendor is allowed to feature product listings.')),
                ('has_dedicated_support', models.BooleanField(default=False, help_text='Whether this vendor has priority 24/7 dedicated support.')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicpages.pricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Subscription',
                'verbose_name_plural': 'Vendor Subscriptions',
                'db_table': 'payments_vendor_subscriptions',
            },
        ),
    ]
