# Generated by Django 6.0.2 on 2026-04-03 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_vendorsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('gradient', models.CharField(blank=True, help_text='e.g. from-blue-600 to-indigo-600', max_length=100, null=True)),
            ],
            options={
                'db_table': 'payments_vendor_pricing_plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VendorPricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='payments.vendorpricingplan')),
            ],
            options={
                'db_table': 'payments_vendor_pricing_features',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='vendorsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.vendorpricingplan'),
        ),
    ]
