# Generated by Django 6.0.2 on 2026-03-02 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0007_hostel_is_verified"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomtype",
            options={"ordering": ["base_price"]},
        ),
        migrations.AddField(
            model_name="roomtype",
            name="room_category",
            field=models.CharField(
                choices=[("AC", "AC"), ("NON_AC", "Non-AC")],
                default="NON_AC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="sharing_type",
            field=models.IntegerField(
                choices=[
                    (1, "Single Sharing"),
                    (2, "Double Sharing"),
                    (3, "Triple Sharing"),
                    (4, "Four Sharing"),
                    (5, "Five Sharing"),
                ],
                default=1,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together={("hostel", "room_category", "sharing_type")},
        ),
        migrations.AddField(
            model_name="roomtype",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name="roomtype",
            name="capacity",
        ),
    ]
