# Generated by Django 6.0.2 on 2026-03-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomtype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='name',
        ),
    ]
