# Generated by Django 6.0.2 on 2026-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_roomtype_description_remove_roomtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
