# Generated by Django 6.0.2 on 2026-03-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomtype_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='beds_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='total_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
