# Generated by Django 6.0.2 on 2026-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_bed_beds_available_bed_total_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='sharing_type',
            field=models.IntegerField(choices=[(1, 'Single Sharing'), (2, 'Double Sharing'), (3, 'Triple Sharing'), (4, 'Four Sharing')], default=1),
        ),
    ]
