# Generated by Django 6.0.2 on 2026-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_roomtype_sharing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
