# Generated by Django 6.0.2 on 2026-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomtype_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
    ]
