# Generated by Django 6.0.2 on 2026-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_bed_is_deleted_roomtype_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.TextField(blank=True, help_text='Comma-separated bed numbers, e.g., B1, B2, B3', null=True),
        ),
    ]
