# Generated by Django 6.0.2 on 2026-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_consolidate_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='show_this_price',
            field=models.BooleanField(default=False, help_text="Show this room type's price on the hostel card"),
        ),
    ]
