# Generated by Django 6.0.2 on 2026-04-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_roomtype_show_this_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='sharing_type',
            field=models.IntegerField(choices=[(0, 'Private Room'), (1, 'Single Sharing'), (2, 'Double Sharing'), (3, 'Triple Sharing'), (4, 'Four Sharing')], default=1),
        ),
    ]
