# Generated by Django 6.0.2 on 2026-04-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_alter_roomtype_sharing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='features',
            field=models.TextField(blank=True, default='', help_text="Comma-separated room features, e.g. 'Air conditioning included,Privacy pods with curtains,Individual lockable lockers'"),
        ),
    ]
