# Generated by Django 6.0.2 on 2026-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_faqcategory_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_image_size_mb', models.PositiveIntegerField(default=10, help_text='Global maximum size for image uploads in MB.')),
            ],
            options={
                'verbose_name': 'Storage Settings',
                'verbose_name_plural': 'Storage Settings',
            },
        ),
    ]
