# Generated by Django 6.0.2 on 2026-02-27 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_subtitle', models.TextField()),
                ('cta_button_text', models.CharField(max_length=100)),
                ('why_title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_items', to='publicpages.homepage')),
            ],
        ),
    ]
