# Generated by Django 6.0.2 on 2026-02-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0004_contact_contactmessage_contactfaq_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.TextField()),
                ('comparison_title', models.CharField(max_length=255)),
                ('comparison_description', models.TextField()),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_button_text', models.CharField(max_length=100)),
                ('cta_button_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Page',
                'verbose_name_plural': 'Pricing Page',
                'db_table': 'public_pricing',
            },
        ),
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='publicpages.pricing')),
            ],
            options={
                'db_table': 'public_pricing_faq',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='publicpages.pricing')),
            ],
            options={
                'db_table': 'public_pricing_plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='publicpages.pricingplan')),
            ],
            options={
                'db_table': 'public_pricing_features',
                'ordering': ['order'],
            },
        ),
    ]
