# Generated by Django 6.0.2 on 2026-03-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0005_pricing_pricingfaq_pricingplan_pricingfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default="India's Most Trusted Student Hub", max_length=255)),
                ('hero_title_main', models.CharField(max_length=255)),
                ('hero_title_italic', models.CharField(max_length=255)),
                ('hero_title_footer', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('hero_primary_cta_text', models.CharField(default='Explore Hostels', max_length=100)),
                ('hero_primary_cta_url', models.CharField(default='/home', max_length=255)),
                ('hero_secondary_cta_text', models.CharField(default='Our Standards', max_length=100)),
                ('hero_secondary_cta_url', models.CharField(default='#how', max_length=255)),
                ('cities_eyebrow', models.CharField(default='Discover Your Hub', max_length=255)),
                ('cities_title_main', models.CharField(default='Most Popular', max_length=255)),
                ('cities_title_italic', models.CharField(default='Destinations', max_length=255)),
                ('features_eyebrow', models.CharField(default='The LiveHub Advantage', max_length=255)),
                ('features_title_main', models.CharField(default='Everything You Need,', max_length=255)),
                ('features_title_italic', models.CharField(default="Nothing You Don't.", max_length=255)),
                ('features_subtitle', models.TextField()),
                ('how_eyebrow', models.CharField(default='The LiveHub Journey', max_length=255)),
                ('how_title_main', models.CharField(default='Booking Made', max_length=255)),
                ('how_title_italic', models.CharField(default='Simple.', max_length=255)),
                ('how_subtitle', models.TextField()),
                ('testimonials_eyebrow', models.CharField(default='Real Experiences', max_length=255)),
                ('testimonials_title_main', models.CharField(default='Trusted by', max_length=255)),
                ('testimonials_title_italic', models.CharField(default='Thousands', max_length=255)),
                ('cta_bottom_eyebrow', models.CharField(default='Start your journey', max_length=255)),
                ('cta_bottom_title_main', models.CharField(default='Ready for your', max_length=255)),
                ('cta_bottom_title_italic', models.CharField(default='next chapter?', max_length=255)),
                ('cta_bottom_subtitle', models.TextField()),
                ('cta_bottom_button_text', models.CharField(default='Start Exploring', max_length=100)),
                ('cta_bottom_button_url', models.CharField(default='/home', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Page',
                'db_table': 'public_landing_page',
            },
        ),
        migrations.CreateModel(
            name='LandingFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='publicpages.landingpage')),
            ],
            options={
                'db_table': 'public_landing_features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingCityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('count_text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/cities/')),
                ('span_large', models.BooleanField(default=False)),
                ('gradient', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='publicpages.landingpage')),
            ],
            options={
                'db_table': 'public_landing_cities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=50)),
                ('color_gradient', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='publicpages.landingpage')),
            ],
            options={
                'db_table': 'public_landing_stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(max_length=10)),
                ('icon_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='publicpages.landingpage')),
            ],
            options={
                'db_table': 'public_landing_steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingTestimonialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('initial', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='publicpages.landingpage')),
            ],
            options={
                'db_table': 'public_landing_testimonials',
                'ordering': ['order'],
            },
        ),
    ]
