# Generated by Django 6.0.2 on 2026-03-15 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_hostel_is_approved'),
        ('publicpages', '0006_landingpage_landingfeatureitem_landingcityitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
