# Generated by Django 6.0.2 on 2026-03-20 15:57

import Hbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpages', '0007_contactmessage_hostel_contactmessage_is_replied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutteammember',
            name='photo',
            field=models.ImageField(upload_to='about/team/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='landingcityitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='landing/cities/', validators=[Hbackend.utils.validate_image_size]),
        ),
    ]
