# Generated by Django 6.0.2 on 2026-03-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_steps',
            field=models.JSONField(blank=True, default=list, help_text='Define steps like [5, 10, 15] for bulk selection'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('number', 'Numbers/Units'), ('ltr', 'Liters (L)'), ('pkt', 'Packet')], default='number', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
