"""
Django settings for Hbackend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
from django.conf import settings
from django.conf.urls.static import static
import mimetypes
import dj_database_url
import os


mimetypes.add_type("image/webp", ".webp", True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure--s7_)1g@6_kyeb2bxp4b0vvr-a_9c@uuor%d)-z)@&8ee@35l="
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

# SECURITY WARNING: don't run with debug turned on in production!
# if ENVIRONMENT == 'development':
DEBUG = True
# else:
# DEBUG = False


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "hostelin.online",
    "www.hostelin.online",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third Party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    # Local Apps
    "accounts",
    "amenities",
    "locations",
    "hostels",
    "rooms",
    "bookings",
    "reviews",
    "payments",
    "seo",
    "cms",
    "blog",
    "publicpages",
   
#vendors and marketplace

    "marketplace",
     "orders",
    "vendors",
    "django_cleanup.apps.CleanupConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise should be after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "Hbackend.api_middleware.APINoRedirectMiddleware",  # Must be before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Hbackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "Hbackend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ========================
# STATIC & MEDIA
# ========================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Enable WhiteNoise's GZip compression and unique names for static files
STORAGES = {
    "default": {
        "BACKEND": "Hbackend.imagekit_storage.ImageKitStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ========================
# DJANGO REST FRAMEWORK
# ========================

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_FILTER_BACKENDS": ("django_filters.rest_framework.DjangoFilterBackend",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    # 🔥 ADD THIS
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    # login and other troller rated
    # "DEFAULT_THROTTLE_RATES": {
    #     "anon": "1000/minute",
    #     "user": "1000/minute",
    #     "login": "100/minute",
    #     "register": "100/minute",
    # },
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10000/day",
        "user": "10000/day",
        "login": "10000/minute",
        "register": "10000/minute",
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
}


# ========================
# JWT CONFIG
# ========================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}


# ========================
# CORS (For Next.js Frontend)
# ========================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://hostelin.online",
    "https://www.hostelin.online",
]

CORS_ALLOW_CREDENTIALS = True

CORS_EXPOSE_HEADERS = [
    "Set-Cookie",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://hostelin.online",
    "https://www.hostelin.online",
]


# append slash
APPEND_SLASH = True

# ========================
# DEFAULT FIELD TYPE
# ========================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Increase max upload size to avoid early rejection (actual limit handled by StorageSettings)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB

# Railway Proxy settings
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)

SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)


# ======================
# Gmail (Booking Emails)
# ======================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# EMAIL_HOST_USER = "lakklplbros@gmail.com"
# EMAIL_HOST_PASSWORD = "mlun eyoc ipfl svoa"

# DEFAULT_FROM_EMAIL = "LiveHub <lakklplbros@gmail.com>"


EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = f"Hostel In <{EMAIL_HOST_USER}>"


# BREVO_FROM_EMAIL = "Hostelin <noreply@hostelin.online>"

# ======================
# Brevo (OTP Emails)
# ======================
BREVO_FROM_EMAIL = "Hostelin <lakklplbros@gmail.com>"

# brevo email config
BREVO_EMAIL_CONFIG = {
    "EMAIL_HOST": "smtp-relay.brevo.com",
    "EMAIL_PORT": 587,
    "EMAIL_USE_TLS": True,
    "EMAIL_HOST_USER": config("BREVO_SMTP_USER"),
    "EMAIL_HOST_PASSWORD": config("BREVO_SMTP_PASSWORD"),
}


# payment  ikeys
RAZORPAY_KEY_ID = config("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET")
RAZORPAY_WEBHOOK_SECRET = config("RAZORPAY_WEBHOOK_SECRET", default="")


# ImageKit Settings
IMAGEKIT_PUBLIC_KEY = config("IMAGEKIT_PUBLIC_KEY")
IMAGEKIT_PRIVATE_KEY = config("IMAGEKIT_PRIVATE_KEY")
IMAGEKIT_URL_ENDPOINT = config("IMAGEKIT_URL_ENDPOINT")

# ========================
# REVIEW SETTINGS
# ========================
# Set to True to make reviews visible immediately, or False to require Admin approval
REVIEWS_AUTO_APPROVE = config("REVIEWS_AUTO_APPROVE", default=False, cast=bool)
# Timer for review publication delay (in seconds).
REVIEWS_PUBLISH_DELAY = config("REVIEWS_PUBLISH_DELAY", default=0, cast=int)
