# Generated by Django 6.0.2 on 2026-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_user_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
    ]
