# Generated by Django 6.0.2 on 2026-03-20 15:57

import Hbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_deleted_verificationcode_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[Hbackend.utils.validate_image_size]),
        ),
    ]
