# Generated by Django 6.0.2 on 2026-03-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('hostel_owner', 'Hostel Owner'), ('vendor', 'Vendor')], default='guest', max_length=20),
        ),
    ]
