# Generated by Django 6.0.2 on 2026-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
