# Generated by Django 6.0.2 on 2026-03-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_canonical_url_blogpost_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
