# Generated by Django 6.0.2 on 2026-03-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_is_indexed_blogpost_og_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_deleted',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0),
        ),
    ]
