# Generated by Django 6.0.2 on 2026-03-20 15:57

import Hbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_is_deleted_blogcategory_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(upload_to='blog/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
    ]
