# Generated by Django 6.0.2 on 2026-02-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelimage',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hostel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hostels', to='amenities.amenity'),
        ),
    ]
