# Generated by Django 6.0.2 on 2026-02-25 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_remove_hostelimage_amenities_hostel_amenities'),
        ('locations', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='locations.area'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
