# Generated by Django 6.0.2 on 2026-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_area_hostel_postal_code_hostel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
