# Generated by Django 6.0.2 on 2026-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_hostelimage_image2_hostelimage_image3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultHostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='hostels/defaults/', verbose_name='Default Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 4')),
                ('alt_text', models.CharField(default='Default hostel image', help_text='Alt text used for all default images', max_length=255)),
            ],
            options={
                'verbose_name': 'Default Hostel Image',
                'verbose_name_plural': 'Default Hostel Images',
            },
        ),
    ]
