# Generated by Django 6.0.2 on 2026-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_defaulthostelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_toprated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
