# Generated by Django 6.0.2 on 2026-03-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_hostel_is_toprated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
