# Generated by Django 6.0.2 on 2026-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_hostel_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('co_living', 'Co-Living Hostel'), ('working_professional', 'Working Professionals Hostel'), ('student', 'Student Hostel'), ('luxury', 'Luxury Hostel'), ('budget', 'Budget Hostel'), ('pg', 'PG Accommodation')], db_index=True, default='boys', max_length=30),
        ),
    ]
