# Generated by Django 6.0.2 on 2026-03-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0008_hostel_hostel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('co_living', 'Co-Living Hostel'), ('working_professional', 'Working Professionals Hostel'), ('student', 'Student Hostel'), ('luxury', 'Luxury Hostel'), ('budget', 'Budget Hostel'), ('pg', 'PG Accommodation')], max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='hostel-type-images/')),
                ('alt_text', models.CharField(default='Hostel type image', max_length=255)),
            ],
        ),
    ]
