# Generated by Django 6.0.2 on 2026-03-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0009_hosteltypeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
