# Generated by Django 6.0.2 on 2026-03-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_alter_hostel_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/hostels/'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='og_type',
            field=models.CharField(default='website', max_length=50),
        ),
        migrations.AddField(
            model_name='hostel',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
