# Generated by Django 6.0.2 on 2026-03-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0012_hostel_canonical_url_hostel_is_indexed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='discounted_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
