# Generated by Django 6.0.2 on 2026-03-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_hostel_discounted_price_per_day_hostel_price_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ['-is_discounted', '-created_at']},
        ),
    ]
