# Generated by Django 6.0.2 on 2026-03-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0014_alter_hostel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
