# Generated by Django 6.0.2 on 2026-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_hostel_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/'),
        ),
    ]
