# Generated by Django 6.0.2 on 2026-03-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0016_hostelimage_image10_hostelimage_image5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 10'),
        ),
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 5'),
        ),
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 6'),
        ),
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 7'),
        ),
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 8'),
        ),
        migrations.AddField(
            model_name='defaulthostelimage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 9'),
        ),
    ]
