# Generated by Django 6.0.2 on 2026-03-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0017_defaulthostelimage_image10_defaulthostelimage_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', verbose_name='Default Image 1'),
        ),
    ]
