# Generated by Django 6.0.2 on 2026-03-20 15:57

import Hbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0019_hostel_is_deleted_hostelimage_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 1'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 10'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 2'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 3'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 4'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 5'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 6'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 7'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 8'),
        ),
        migrations.AlterField(
            model_name='defaulthostelimage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/defaults/', validators=[Hbackend.utils.validate_image_size], verbose_name='Default Image 9'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=models.ImageField(upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='hostels/', validators=[Hbackend.utils.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='hosteltypeimage',
            name='image',
            field=models.ImageField(upload_to='hostel-type-images/', validators=[Hbackend.utils.validate_image_size]),
        ),
    ]
