# Generated by Django 6.0.2 on 2026-03-22 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0020_alter_defaulthostelimage_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('name', models.CharField(max_length=255)),
                ('distance', models.CharField(help_text='e.g., 500m or 1.2km', max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='hostels.hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
