# Generated by Django 6.0.2 on 2026-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0021_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='food_rating_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='hostel_rating_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hostel',
            name='room_rating_avg',
            field=models.FloatField(default=0),
        ),
    ]
