# Generated by Django 6.0.2 on 2026-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0022_hostel_food_rating_avg_hostel_hostel_rating_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelimage',
            name='provider',
            field=models.CharField(choices=[('imagekit', 'ImageKit'), ('cloudinary', 'Cloudinary')], default='imagekit', max_length=20),
        ),
    ]
