# Generated by Django 6.0.2 on 2026-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0024_alter_imagefield_max_length_500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('co_living', 'Co-Living Hostel'), ('working_professional', 'WorkingProfessionalsHostel'), ('student', 'Student Hostel'), ('luxury', 'Luxury Hostel'), ('budget', 'Budget Hostel'), ('pg', 'PG Accommodation')], db_index=True, default='boys', max_length=30),
        ),
        migrations.AlterField(
            model_name='hosteltypeimage',
            name='hostel_type',
            field=models.CharField(choices=[('boys', 'Boys Hostel'), ('girls', 'Girls Hostel'), ('co_living', 'Co-Living Hostel'), ('working_professional', 'WorkingProfessionalsHostel'), ('student', 'Student Hostel'), ('luxury', 'Luxury Hostel'), ('budget', 'Budget Hostel'), ('pg', 'PG Accommodation')], max_length=30, unique=True),
        ),
    ]
