# Generated by Django 6.0.2 on 2026-04-15 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0025_alter_hostel_hostel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('charge_type', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('maintenance', 'Maintenance'), ('wifi', 'WiFi'), ('laundry', 'Laundry'), ('other', 'Other')], default='electricity', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_charges', to='hostels.hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
