# Generated by Django 6.0.2 on 2026-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0026_extracharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='suitable_for',
            field=models.CharField(choices=[('student', 'Student'), ('job_holder', 'Job Holder'), ('working_professional', 'Working Professional'), ('both', 'Both (Student & Professional)'), ('anyone', 'Anyone')], db_index=True, default='anyone', max_length=50),
        ),
    ]
