# Generated by Django 6.0.2 on 2026-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0028_alter_hostel_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI-generated marketing description for this hostel.', null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last AI description generation.', null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ai_hash',
            field=models.CharField(blank=True, db_index=True, help_text='MD5 hash of key hostel fields. Used for change detection.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='ai_version',
            field=models.PositiveSmallIntegerField(default=1, help_text='Prompt version. Increment to force regeneration across all hostels.'),
        ),
    ]
