# Generated by Django 6.0.2 on 2026-03-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
