# Generated by Django 6.0.2 on 2026-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='food_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='hostel_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='room_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
