# Generated by Django 6.0.2 on 2026-03-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_type',
            field=models.CharField(choices=[('rice', 'Rice & Grains'), ('vegetables', 'Vegetables & Fruits'), ('dairy', 'Milk & Dairy Products'), ('eggs', 'Eggs'), ('meat', 'Meat & Poultry'), ('kirana', 'Kirana / General Store'), ('oil', 'Cooking Oil & Spices'), ('bakery', 'Bakery & Bread'), ('water', 'Drinking Water Supply')], db_index=True, default='general', max_length=50),
        ),
    ]
