# Generated by Django 6.0.2 on 2026-03-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_vendor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_types',
            field=models.JSONField(blank=True, default=list, help_text='Selected vendor types/categories'),
        ),
    ]
