# Generated by Django 6.0.2 on 2026-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities'),
        ),
    ]
