# Generated by Django 6.0.2 on 2026-03-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['slug', 'city'], name='locations_a_slug_5427c9_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['slug'], name='locations_c_slug_0d00a7_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['slug'], name='locations_c_slug_390e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['slug'], name='locations_s_slug_c8a448_idx'),
        ),
    ]
