# Generated by Django 6.0.2 on 2026-03-20 15:57

import Hbackend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_area_slug_alter_city_slug_alter_country_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities', validators=[Hbackend.utils.validate_image_size]),
        ),
    ]
