# Generated by Django 6.0.2 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_area_is_deleted_city_is_deleted_country_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
