# Generated by Django 6.0.2 on 2026-04-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Original user question')),
                ('normalized_question', models.TextField(db_index=True, help_text='Normalized version for matching similar questions')),
                ('answer', models.TextField(help_text='AI generated answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chat Caches',
            },
        ),
    ]
