# Generated by Django 6.0.2 on 2026-04-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcache',
            name='normalized_question',
            field=models.CharField(db_index=True, help_text='Normalized version for matching similar questions', max_length=500),
        ),
    ]
