# Generated by Django 6.0.2 on 2026-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('stay', 'Stay'), ('visit', 'Visit')], default='stay', max_length=10),
        ),
    ]
