# Generated by Django 6.0.2 on 2026-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stay_duration',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('1_month', '1 Month'), ('2_months', '2 Months'), ('3_months', '3 Months'), ('4_months', '4 Months'), ('5_months', '5 Months'), ('gt_5_months', 'More than 5 Months')], default='none', max_length=20, null=True),
        ),
    ]
