# Generated by Django 6.0.2 on 2026-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_payment_method_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
