# Generated by Django 6.0.2 on 2026-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_hostelinquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelinquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('enquired', 'Enquired'), ('responded', 'Responded'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
