# Generated by Django 6.0.2 on 2026-02-25 02:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seometa',
            name='is_indexed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seometa',
            name='robots_directives',
            field=models.CharField(blank=True, help_text='Example: noindex, nofollow', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seometa',
            name='structured_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
