# Generated by Django 6.0.2 on 2026-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_seometa_created_at_seometa_is_indexed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seometa',
            name='meta_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
