# Generated by Django 6.0.2 on 2026-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the broadcast notification', max_length=255)),
                ('message', models.TextField(help_text='Message body that will be sent to ALL users')),
                ('link', models.CharField(blank=True, help_text='Optional: URL to redirect user when clicked', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='True if it has been sent out to users')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
