# Generated by Django 6.0.2 on 2026-04-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_broadcastnotification'),
        ('vendors', '0003_remove_vendor_vendor_type_vendor_vendor_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.IntegerField(choices=[(0, 'Active'), (1, 'Deleted')], default=0)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('order', 'New Order Received'), ('payment', 'Payment Received'), ('product', 'Product Update'), ('system', 'System Alert')], default='order', max_length=20)),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_notifications', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
